### PR TITLE
Add directives pubids to tests

### LINKED ISSUE #57: (URGENT) Parsing of ISO/IEC Directives necessary
We have new documents in the relaton-data-iso repo and pubis-iso fails with the IDs like `ISO IEC DIR 1`
https://github.com/relaton/relaton-iso/runs/6880704298?check_suite_focus=true#step:6:249

All new IDs:
- `ISO/IEC DIR 1` or reference `ISO IEC DIR 1`
- `ISO/IEC DIR 1 ISO SUP` or reference `ISO IEC DIR 1 ISO SUP`
- `ISO/IEC DIR 2 ISO` or reference `ISO IEC DIR 2 ISO`
- `ISO/IEC DIR JTC 1 SUP` or reference `ISO IEC DIR JTC 1 SUP`

### PR DESCRIPTION
**Pull request by mico**
closes #57

### CODE REVIEW

**Comment by ronaldtse** [comment]
@mico is this ready to go?

**Comment by mico** [comment]
> @mico is this ready to go?

yes, now it's ready

**Review by ronaldtse — APPROVED** [review]
Thank you @mico !

**Comment by ronaldtse** [comment]
Thank you @mico! Let's make a release too. Thanks.

**Pull request merged**
