### PR TITLE
Add documentation on how to create identifiers

### LINKED ISSUE #54: Provide documentation on how to create identifiers using gem
As requested by @opoudjis https://github.com/metanorma/metanorma-iso/issues/657#issuecomment-1146028990

### PR DESCRIPTION
**Pull request by mico**
closes #54 
@opoudjis is it enough or you need more details on every or specific attributes?

### CODE REVIEW

**Comment by opoudjis** [comment]
Not adequate; this is after all meant to be used by not just me. I need:

* an indication of every attribute whose type is not a string; I am assuming a few of these are arrays and can take multiple values; joint_document is presumably boolean
* an explanation of copublisher and when to use it instead of publisher
* why are amendments, corrigendums etc plural? Are they expected to be an array? I have trouble seeing why they would be
* what is the distinction between supplement and supplements?
* for every attribute with a controlled vocabulary, I need to know the legal values: I cannot trust that you and I understand the same enums, and they need to be documented in any case
* what is dirtype?

**Comment by mico** [comment]
@ronaldtse @opoudjis what do you think about this? Is something missing?

**Comment by opoudjis** [comment]
Ok, that's a lot cleaner, thank you. I'd have preferred prose, but I can use this.

**Review by opoudjis — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thank you @mico @opoudjis !

**Pull request merged**
